version: '2'
services:
  web:
    build: .
    image: jrs
    container_name: jrs
    depends_on:
    - "mysql-frs"
    environment:
    - SERVER_HOST=0.0.0.0
    - SERVER_PASSWD=admin
    - JS_DB_HOST=mysql-jrs
    - JS_DB_PORT=3306
    - JS_DB_USER=root
    - JS_DB_PASSWORD=my_password
    links:
    - "mysql-frs:mysql"
    ports:
    - "8080:8080"
  mysql-frs:
    container_name: mysql-jrs
    image: "mysql:5.5"
    environment:
    - MYSQL_ROOT_PASSWORD=my_password
    ports:
    - "3307:3306"